name: Generate Snake Animation

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: Kaiobasx
          outputs: |
            dist/snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake-svg
          path: dist/snake.svg

      - name: Push snake animation to output branch
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "update snake animation"
          add: dist/snake.svg
